const Sections = new Set()
Sections.add('[INFO]')
Sections.add('[RUNWAY]')
Sections.add('[VOR]')
Sections.add('[NDB]')
Sections.add('[AIRPORT]')
Sections.add('[FIXES]')
Sections.add('[ARTCC]')
Sections.add('[ARTCC HIGH]')
Sections.add('[ARTCC LOW]')
Sections.add('[GEO]')
Sections.add('[SID]')
Sections.add('[STAR]')
Sections.add('[REGIONS]')
Sections.add('[LOW AIRWAY]')
Sections.add('[HIGH AIRWAY]')
Sections.add('[LABELS]')

module.exports = Sections